### ISSUE TITLE
PXD-1727 ⁃ List with params returns half the limit when using multiple params

### ISSUE THREAD

**Issue by zflamig** [uc-cdis/indexd#158]
Reported by GDC.

**Comment by madopal** [comment]
I have more on this, I'll get information in as soon as I get a moment to breathe. But it's related to the urls_metadata table having N entries, but they get deduped when returning the dict.

**Comment by philloooo** [comment]
➤ Alex commented:

After this: [https://github.com/uc-cdis/indexd/blob/master/indexd/index/drivers/alchemy.py#L378-L383](https://github.com/uc-cdis/indexd/blob/master/indexd/index/drivers/alchemy.py#L378-L383)

a SELECT 1 FROM ... is added to the query (which makes me think this is where the issue is)??

This is what gets added to the query after that: 

... AND (EXISTS (SELECT 1
FROM index_record_url_metadata
WHERE index_record_url.url = index_record_url_metadata.url AND index_record_url.did = index_record_url_metadata.did AND index_record_url_metadata."key" = ? AND index_record_url_metadata.value = ?))

**Comment by philloooo** [comment]
➤ Alex commented:

either that or it's an issue when the LIMIT gets applied at the end, idk. I didn't get too deep into debugging
