### ISSUE TITLE
add a `type` property to IndexRecordURL and another model to store controlled enum in db

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/indexd#41]
we need a separate field to describe the purpose of the data that's from a list of types that make sense to the system.
This field is needed to make services able to infer the purpose of that storage location. eg:
- on_premises_cold_storage
- on_premises_primary_storage
- amazon_backup
- amazon_primary_storage

**Comment by zflamig** [comment]
How do you plan on determining the best location to download from though? It probably makes the most sense to associate some sort of cost with these?

**Comment by zflamig** [comment]
Makes sense, I'm just wondering how to best do that?
Also EDC make have data on AWS, GCP, Azure, Griffin, NCSA, RCC, etc so we probably don't want such explicit names for the locations?

Given both of those I feel like there should be some sort of "cost" on each URL still. This could be the cost of egress per gb, or for cold storage ones the cost of egress+read? Then the client or API could have some logic to determine locality and if the data doesn't exist locally serve from the cheapest source first?

**Comment by frickjack** [comment]
I'm not familiar with the system (new guy), so sorry if I'm way off here:

o It's a good idea to have a "purpose" field attached to each location, so "offline_backup" for data in amazon glacier, "region_replica" for an S3 replica:
      https://aws.amazon.com/blogs/aws/new-cross-region-replication-for-amazon-s3/

o If we have multiple copies of the same data, then we should mark the "master" somehow

o We should store the master (expected) md5 or some other hash on each location someplace

o it's a good idea to have some way to determine where that data actually is, so:
        https://data.some-commons.org/data/byid/1244aa
   - where is that ?
   Maybe have a locationURI field:
       s3://bucketid/object-path

o It's a good idea for us to serve data to a user accessing the data via the public internet over a CDN:
     http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/PrivateContent.html

o It's a good idea for us to somehow make data available to clients running in AWS via S3 directly, not going over the public internet.  Similarly for Google Cloud, Azure, whatever.  

o It's a good idea to put a cost on a location, but the cost depends on where the client is running (which part of the world, within a particular public cloud, whatever ...), so maybe instead of a static cost - have some kind of a weight-function that the client evaluates, so accessing an S3 bucket in Virginia directly might be:
         cost = inAWS ? 0 : inUnitedStates ? 10 : 100

**Comment by trevars** [comment]
Decided to go with generic json to store all the metadata. Closing.
